### ISSUE TITLE
Calculate Win: Flashlight Fish

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#12]
This challenge is won when:

`#creature_flashlight-fish1`’s `animation-play-state` goes from `paused` to `running`

_OR_ 

the first time `animationiteration` fires on the element.

(I think the latter is preferable.)

**Comment by nearestnabors** [comment]
This seems to be working. Potch, worthy of closing?

**Comment by potch** [comment]
Indeed!
