### ISSUE TITLE
Calculate Win: Nautilus

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#13]
This challenge is won when:

For `#creature_nautilus1`

it's `animation-timing-function`

is `cubic-bezier()` 

and at least one of `cubic-bezier()`'s four values is a negative value. That indicates a "bounce" easing/is close enough.

**Comment by potch** [comment]
This is working!

**Comment by nearestnabors** [comment]
It wasn't! But I fixed it :dancer:

**Comment by nearestnabors** [comment]
Maybe a weird commit or something? It was watching the flashlight fish.
