### ISSUE TITLE
reveal.ogg for bloop

### ISSUE THREAD

**Issue by operatorjen** [tinmagpie/deepdev#15]
only play once on discovery, never again.

**Comment by nearestnabors** [comment]
This is for the `#the-bloop`, our injected squid.

It will be injected, so event listeners will need to be high up on the DOM or attached on delivery. See squid tasks for more information about conditional FF-only loading.

**Comment by mythmon** [comment]
The event bindings are done with bloop.js which is lazy loaded at the same time as the images and sounds, so the DOM is ready to be bound to.

**Comment by mythmon** [comment]
Oh, and I stole a bunch of stuff from `audiotest.html`. That should probably be done better so it is re-usable by the rest of the code.

**Comment by nearestnabors** [comment]
Are the bloop files only queued for FireFox users? 

They're quite large. Would be mean of us to suck up people's bandwidth if they're checking in on their mobile phones and have no possibility of completion!

**Comment by mythmon** [comment]
Yes (now that I fixed it) the audio and sprite files are all loaded from `bloop.html`, a snippet that only loads after half the goals are finished, and only loads for Firefox users.
