### ISSUE TITLE
Calculate Win: Disco Fish

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#17]
This challenge is won when:

Paths inside `#d2600` (referenced via CSS as `#d2600 path`)

change their `fill` from `transparent` to `#56fddb`

_Concern_ People using the eyedropper tool might not get an exact match if they pick a pixel bordering on another pixel. Is there a way to test for how bright it is? Other possibility: just look for the value to change to a hex value period.

**Comment by potch** [comment]
I'm checking for "any change to the fill", which is fairly effective.

Question- the challenge wants you to scroll back up to Flashlight Fish to get the sample, who is already in motion. This is... tricky. Any other place we can sample the color?

**Comment by nearestnabors** [comment]
This is the UI I'm working on tonight: the flashlight fish and it's cheek
will be in there for sampling!

**Comment by potch** [comment]
This is working- love the zoomed-in UI :)

**Comment by nearestnabors** [comment]
Saved the best for last ;)
