### ISSUE TITLE
Calculate Win: Vomiting Shrimp

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#18]
Considering making this a transition, not an animation.

`#creature_vomiting-shrimp1`'s animation runs every time it’s scrolled into view thanks to the .in-view class added to its parent div via `main.js.` 

The `animation-name` for this: `escapingGloriously`

Users are to "rewind" the animation to its starting point.

Patrick Brosset might have ideas on how to test for this.

It may be easier to use transitions. Or animations. Do tell.

**Comment by nearestnabors** [comment]
This is now a duplicate. I'll update it.

**Comment by potch** [comment]
I'm checking for the fact that the shrimp is `in-view` and has been reset to its initial position. Works pretty well!
