### ISSUE TITLE
Calculate Win: Hagfish

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#19]
This one is difficult.

The goal is to use the animation panel to see things that are animating but might be obscured by other things on the page layered over them or opacity.

`#creature_hagfish1` is hidden in the gross ooze at the bottom of the sea with positioning right now.

I have it set so that when you remove it's `bottom` sizing, it pops up on top of the ooze where you can see it.

Problem is, if people right click on the ooze, this fish won't show in the animation panel at all, because that panel shows children elements with animations. Ain't no way to layer the ooze over the hagfish and have it also be a child of that ooze.

So I'm considering setting the hagfish's `opacity` to 0. Then, when it's changed to 1 or the `opacity` property is removed, the challenge is won.

I'm open to other suggestions, too, of course. Really liked the idea of burying it in the ooze!

**Comment by potch** [comment]
we can put some ooze over top of it that obscures it, but has `pointer-events: none` set on said ooze so the mouse will pass through it and allow us to select the hagfish directly.

**Comment by nearestnabors** [comment]
Holy crow, that changed everything!

**Comment by nearestnabors** [comment]
Ok, hagfish has been updated. Now to calculate the win, her `bottom` value must be > 100px.

**Comment by potch** [comment]
This is also working!
