### ISSUE TITLE
If someone is not on Firefox, display the logo (or apply a comment overlay) about downloading DE

### ISSUE THREAD

**Issue by operatorjen** [tinmagpie/deepdev#22]
<img width="527" alt="vidyodesktop" src="https://cloud.githubusercontent.com/assets/83059/10495392/7a73fe58-7270-11e5-93ba-fc59603ad005.png">

Similar to the above messaging (just replace with animation instead of performance), this should show up when someone is not on FF DE. It is open ended on whether you want to use the Firefox logo or whether you want it to point to the wordmark.

**Comment by operatorjen** [comment]
Wordmark / logo should link to https://www.mozilla.org/firefox/developer/

**Comment by nearestnabors** [comment]
I need the logo in order to make this.
