### ISSUE TITLE
Compare and apply heights of .copy and .challenge.

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#23]
`.challenge` is supposed to overlay `.content` when it's toggled on via "Start challenge!" Both have slightly different levels of content. Would be great to measure the heights of both, and set the shorter to the same height as the larger.

Of course, this must be recalculated on page and font resizes and such.

**Comment by mythmon** [comment]
I know how to do retriggering on page size (we've got that already). How do we detect change of font size?

**Comment by nearestnabors** [comment]
I was hoping you could tell me! I was trying to figure that one out.

We can just expect people to do a refresh, too.

**Comment by nearestnabors** [comment]
Going to hit pause on this one for now. Looks like having the fish INSIDE the challenge is not such a bad thing :)

**Comment by nearestnabors** [comment]
Closing because it just doesn't matter anymore.
