### ISSUE TITLE
Deep Sea Disco jumps abruptly when right-click-inspected

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#48]
In Nightly, right-click inspect the dragonfish's photophore. Notice how the page jumps down, hiding the dragon fish when the devvtools pop up. Dragonfish's head should remain visible.

**Comment by potch** [comment]
This is working to a pretty good standard. Takes about 100 lines of javascript to account for viewport-based sizing having weird interaction with scroll/window-resize.
