### ISSUE TITLE
Smallen the videos

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#49]
They're kinda big, filesize-wise. Hey, Jenn, you got those videos super small. Think you can help these? Also, check to make sure they look good, no glitches or weird or confusing transitions.

**Comment by operatorjen** [comment]
@rachelnabors i've added smaller videos for each of them and appended those with -sm - have a look at the quality - it is slightly blurrier as the quality is not as high but the size is significantly smaller. feel free to rename to the original copies if you're happy with these.
