### ISSUE TITLE
Add social sharing

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#7]
It needs a way to share it with your friends as requested by Arcadio.

**Comment by operatorjen** [comment]
I've added this into index.html with the correct short URLs and requirements as per Arcadio. It'll definitely need some padding / layout fixes but I'll close this for now.

**Comment by operatorjen** [comment]
Replace ShareThis with other icons - make sure the links to share point to http://mzl.la/devtoolschallenger
