### ISSUE TITLE
Progress bar behavior

### ISSUE THREAD

**Issue by nearestnabors** [tinmagpie/deepdev#9]
There's a UI component in the HTML, `nav.progress`.

Every time a person completes a task, its corresponding li should get a class of `.completed.`

When the `inView` function in `main.js` fires over the corresponding task, the li should get a class of `.visited` (this only needs to happen once per task, it makes its UI component show).

**Comment by potch** [comment]
I've implemented the scroll-into-view portion of this, going to create stub goals for each task now.

**Comment by nearestnabors** [comment]
I can confirm that the scroll into view portion is working as expected.

**Comment by potch** [comment]
Confirming goals receive class of "complete" when the goal is completed successfully.
